name: Renovate-scheduler
on:
#   schedule:
#     - cron: '0 3 * * *'   # every day at 3 AM UTC
  workflow_dispatch:      # allow manual runs

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Renovate run
        uses: renovatebot/github-action@v43.0.12
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: SumoLogic/sumologic-otel-collector
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate.json5
