name: Renovate-scheduler
on:
  schedule:
    - cron: '0 3 * * 2'   # every Tuesday at 3 AM UTC
  workflow_dispatch:      # allow manual runs

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Renovate run
        uses: renovatebot/github-action@v46.1.1
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: SumoLogic/sumologic-otel-collector
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: renovate.json5
